version: '3.8'

services:
  db:
    image: postgres:15  
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recipe_suggestion_solution
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./recipedata.csv:/docker-entrypoint-initdb.d/recipedata.csv
      - ./ingredientsdata.csv:/docker-entrypoint-initdb.d/ingredientsdata.csv
      - ./recipe_ingredientsdata.csv:/docker-entrypoint-initdb.d/recipe_ingredientsdata.csv
      - ./student_housedata.csv:/docker-entrypoint-initdb.d/student_housedata.csv
      - ./fridge_contentsdata.csv:/docker-entrypoint-initdb.d/fridge_contentsdata.csv


  # createdatabase:
  #   build:
  #     context: .       
  #     dockerfile: Dockerfile
  #   environment:
  #     MAIN_CLASS: org.example.CreateDatabase
  #   depends_on:
  #     - db


  # recipeselectionpage:
  #   build:
  #     context: .       
  #     dockerfile: Dockerfile
  #   environment:
  #     MAIN_CLASS: org.example.RecipeSelectionPage
  #   depends_on:
  #     - db
      
  app:
    build:
      context: .       
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MAIN_CLASS: org.example.Application    
    depends_on:
      - db

  frontend: 
    build:
      context: ./src/main/frontend/gui
      dockerfile: Dockerfile 
    ports: 
      - "3000:80" 
    depends_on: 
      - app 

volumes:
  db-data:


