version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recipe_suggestion_solution
    volumes:
      - db-data:/var/lib/postgresql/data
      #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./src/main/resources:/data:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      timeout: 3s

  createdatabase:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MAIN_CLASS: org.example.CreateDatabase
    depends_on:
      db:
        condition: service_healthy

  recipeselectionpage:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MAIN_CLASS: org.example.RecipeSelectionPage
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      MAIN_CLASS: org.example.App
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: recipe_suggestion_solution

volumes:
  db-data:
