name: "PRP Java CI Custom Workflow"

on:
  push:
    branches:
      - main
    pull_request:
    workflow_dispatch:

jobs:
  build:
  name: "Build"
  runs-on: "ubuntu-latest"

steps:
  - name: "Clone repo"
    uses: actions/checkout@V4

  - name: "Build project"
    run: ./gradlew build