/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;
import org.junit.jupiter.api.Test;

class CreationTest {
    @Test void testCreation() {
        String url = "jdbc:postgresql://localhost:5432/postgres";
        String user = "postgres";
        String password = "password";
        try (Connection conn = DriverManager.getConnection(url, user, password)) {
            assertNotNull(conn, "Should have a Connection");
            try (Statement stmt = conn.createStatement()) {
                String sql = "SELECT * FROM fridge_contents";
                try (ResultSet rs = stmt.executeQuery(sql)) {
                    boolean hasData = rs.next(); 
                    assertTrue(hasData, "The fridge_contents table should not be empty!!!!");//if not even one row exists, error
                }
            }
        } catch (Exception e) {
            fail("Failed to create the database: " + e.getMessage());
        }
    }
}

