# Workflow (update build) to run whenever we update main
name: "Update Docker Build"
on:
  push:
    branches:
      - main
      - add/docker-ci
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    permissions:
      packages: write
      contents: read

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Run Gradle build"
        run: gradle installDist

      - name: "Debug Gradle output"
        run: |
          echo "Listing Gradle build output:"
          ls -R build/install
          echo "Checking if app directory exists:"
          ls -la build/install/<application-name>/bin

      - name: "Configure Docker metadata using Docker/metadata-action"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/Yellowjeebz/PRP-Recipe-Suggestion-Solution
          tags: |
            type=sha
            type=raw,value=latest

      - name: "Authenticate with Docker"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Set up Docker buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Build and upload the Docker image"
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
