name: "PRP RSS Custom Java CI Workflow"

on:
  push:
    branches:
      - main
    pull_request:
    workflow_dispatch:
    
jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        java-version: [8, 17, 21, 23]
    
    steps:
      - name: "Clone repo"
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}
          cache: "gradle"
      
      - name: "Build project"
        run: ./gradlew build

      - name: "Test project"
        run: ./gradlew test

      - uses: actions/upload-artifact@v4
        with:
          path: build/libs/*.jar
          name: build-artifacts
